---
# BGP Configurations
- hosts: "ceos"
  gather_facts: false
  connection: "network_cli"
##
  vars_files:
    - vars/group_vars/ceos.yml
    - vars/host_vars/ceos1.yml
    - vars/host_vars/ceos2.yml
  tasks:
    - name: Configure Interfaces
      ansible.builtin.include_tasks:
        file: tasks/intf.yml
    - name: Configure protocols
      ansible.builtin.include_tasks:
        file: tasks/bgp.yml
    - name: save EOS running to startup config after modifying
      eos_config:
        save_when: modified