---
# BGP Configurations
- hosts: "ceos"
  gather_facts: false
  connection: "network_cli"
  become: true
##
  vars_files:
    - group_vars/ceos.yml
    - host_vars/clab-lab-01-ceos1.yml
    - host_vars/clab-lab-01-ceos2.yml
  tasks:
    - name: Configure Interfaces
      ansible.builtin.include_tasks:
        file: tasks/intf.yml
    - name: Configure protocols
      ansible.builtin.include_tasks:
        file: tasks/bgp.yml
    - name: save EOS running to startup config after modifying
      eos_config:
        save_when: modified