---
# BGP Configurations
- hosts: "ceos"
  gather_facts: false
  connection: "network_cli"
  become: true
  ##
  tasks:
    - name: Configure Interfaces
      ansible.builtin.include_tasks:
        file: intf.yml
    - name: Configure protocols
      ansible.builtin.include_tasks:
        file: bgp.yml
  # - name: save EOS running to startup config after modifying
  #   eos_config:
  #     save_when: modified