---
# BGP Configurations
- hosts: "ceos"
  gather_facts: false
  connection: "network_cli"
  become: true

  tasks:
    - name: "VALIDATE DEVICES ARE REACHABLE"
      ansible.builtin.ping:
      register: "ping"

    - name: "VIEW OUTPUT OF PING"
      ansible.builtin.debug:
        var: "ping"

    - name: "SHOW VERSION"
      ansible.utils.cli_parse:
        command: "show version"
        parser:
          name: "ansible.netcommon.ntc_templates"
      register: "version_result"

    - name: "{{ inventory_hostname | upper }} OS VERSION"
      ansible.builtin.debug:
        msg: "{{ version_result['parsed'][0]['image'] }}"

    - name: "RUN SHOW COMMAND"
      cli_command:
        command: "{{ commands['show_interfaces'] }}"
      register: "show_interfaces"

    - name: "VIEW OUTPUT OF SHOW COMMAND"
      ansible.builtin.debug:
        var: "show_interfaces.stdout_lines"

    - name: Configure routed protocols
      arista.eos.interfaces:
        config:
          - name: "{{ item.eos_if }}"
            mode: layer3
      when:
        - item.routed is defined
      loop: "{{ interfaces }}"

    - name: Configure interface state and descriptions
      arista.eos.interfaces:
        config:
          - name: "{{ item.eos_if }}"
            description: "{{ item.desc }}"
            enabled: "{{ item.enabled }}"
      loop: "{{ interfaces }}"

    - name: Configure L3 IPv4 Interfaces
      arista.eos.l3_interfaces:
        config:
          - name: "{{ item.eos_if }}"
            ipv4:
            - address: "{{ item.ipv4 }}"
      when:
        - item.ipv4 is defined
      loop: "{{ interfaces }}"

    - name: Enable IPv4 routing
      eos_config:
        lines:
          - "ip routing"

    - name: Configure BGP - iBGP v4 peers
      arista.eos.eos_bgp:
        config:
          bgp_as: "{{ bgp['local_as'] }}"
          log_neighbor_changes: True
          router_id: " {{ router_id }}"
          neighbors:
          - neighbor: "{{ item.neighbor }}"
            remote_as: "{{ item.remote_as }}"
      when:
        - bgp is defined
      loop: "{{ bgp.neighbors.ipv4_neighbors }}"