---
# BGP Configurations
- hosts: "ceos"
  gather_facts: false
  connection: local
  ##
  tasks:
  - import_role:
      name: interfaces
  - import_role: 
      name: routeprotocols
  - name: save EOS running to startup config after modifying
    eos_config:
      save_when: modified