---
# BGP Configurations
- hosts: "ceos"
  gather_facts: false
  connection: "network_cli"
  ##
  tasks:
  - import_role:
      name: interfaces
  - import_role: 
      name: routeprotocols
  - name: save EOS running to startup config after modifying
    arista.eos.eos_config:
      save_when: modified