---
- name: "GET NOKIA SR LINUX DATA"
  hosts: "srl"
  gather_facts: false
  connection: "network_cli"

  vars:
    cli:
      host: "srl"
      username: admin
      password: NokiaSrl1!
      transport: cli

  tasks:
    - name: "run show version on remote device"
      community.network.nos_command:
        commands: "show version"
        provider: "{{ cli }}"
      register: show_ver
      when: ansible_network_os == 'community.network.nos'
        