---
- name: "GET NOKIA SR LINUX DATA"
  hosts: "srl"
  gather_facts: false
  connection: local

  vars:
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: "run show version NOS"
      sros_command:
        commands:
          - show version
        provider: "{{ cli }}"
    # - name: "run show version on remote device"
    #   community.network.nos_command:
    #     commands: "show version"
    #   register: show_ver
    #   when: ansible_network_os == 'community.network.nos'
        