---
- name: GET STATE DATA FROM SR LINUX
  hosts: srl
  gather_facts: false
  connection: local

  tasks:
    - name: "get hostname and version"
      ansible.builtin.uri:
        url_username: admin
        url_password: NokiaSrl1!
        method: POST
        body:
          jsonrpc: "2.0"
          id: 1
          method: get
          params:
            datastore: state
            commands:
              - path: /system/name/host-name
              - path: /system/information/version
              - path: /system/json-rpc-server/network-instance[name=mgmt]/https/tls-profile
              datastore: running
        body_format: json
      register: get_results

    - ansible.builtin.debug:
        msg: "Host {{get_results.json.result[0]}} runs {{get_results.json.result[1]}} version"