---
- name: "GET STATE DATA FROM SR LINUX"
  hosts: "srl"
  gather_facts: false
  connection: local

  vars:
    commands:
      - info system name host-name
      - info system information
      - info system json-rpc-server network-instance mgmt http

  tasks:
    - name: "get hostname and contact"
      ansible.builtin.uri:
        body:
          jsonrpc: "2.0"
          id: 1
          method: cli
          params:
            datastore: state
            commands: "{{ commands }}"
            output-format: text
        body_format: json
      register: cli_result

    - ansible.builtin.debug:
        msg: "Host {{cli_result.json.result[0]}} contact {{cli_result.json.result[1]}}"