---
- name: "GET STATE DATA FROM SR LINUX"
  hosts: "srl"
  gather_facts: false
  connection: local

  tasks:
    - name: "get hostname and version"
      ansible.builtin.uri:
        url_username: admin
        url_password: NokiaSrl1!
        method: POST
        body:
          jsonrpc: "2.0"
          id: 1
          method: get
          params:
            datastore: state
            commands:
              - path: /system/name/host-name
              - path: /system/information/version
              datastore: running
        body_format: json
      register: get_result

    - ansible.builtin.debug:
        msg: "Host {{get_result.json.result[0]}} runs {{get_result.json.result[1]}} version"